### ISSUE TITLE
Compilation error in generated swift file when protocol have init method. How to use init in protocol?

### ISSUE THREAD

**Issue by mahabaleshwarhnr** [leoture/MockSwift#126]
- [x] I have read the [CONTRIBUTING](https://github.com/leoture/MockSwift/blob/master/CONTRIBUTING.md).  

I have init method in my protocol.   I am getting the below error when sourcery generates the code.
`Keyword 'init' cannot be used as an identifier here. If this name is unavoidable, use backticks to escape it`

### 📝 For Example
```
// sourcery: AutoMockable
protocol DashboardRepository: AnyObject {
    func fetchDashBoard() -> [DashboardItem]
    func updateNotification()
    init(apiclient: APIClient)
}
```
Sourcery generated the code as below:

```
public func init(apiclient: APIClient) -> DashboardRepository {
    mocked(apiclient)
  }
.......
```
### 📝 What is the Question?
How to generate the mock when protocol have init method?

**Comment by mahabaleshwarhnr** [comment]
@leoture can you please help here.

**Comment by leoture** [comment]
Hello @mahabaleshwarhnr !
init cannot be declared in an `extension Mock ... { ... }`. #127 will fix that.
You should create an extension by yourself as bellow:
```
extension  DashboardRepository {
  init(apiclient: APIClient) {
    ...
  }
}
```
