### ISSUE TITLE
MockGiven willThrow

### ISSUE THREAD

**Issue by leoture** [leoture/MockSwift#35]
- [x] I have read the [CONTRIBUTING](https://github.com/leoture/MockSwift/blob/master/CONTRIBUTING.md).  

## 🚀 Describe the feature you'd like
`given(mock).function().willThrow(MyError())`

## 🛠 Describe the implementation you've considered  
A clear and concise description of any implementation solutions you've considered.

**Comment by HEYGUL** [comment]
Can you please add details (examples would be ideal) on this feature ?
I would be glad to contribute on this great project.

**Comment by leoture** [comment]
Hello! Thank you for your interest 😀. I will add more details for next issues from now. For this issue, I have already written the implementation. A pull request will be open today. Don’t hesitate to comment  it.
